In [233]:
#Import all relevant libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore
 
## This statement allows the visuals to render within your Jupyter Notebook.
%matplotlib inline

## Loading the data
We can now load the dataset into pandas using the read_csv() function. This converts the CSV file into a Pandas dataframe.

In [236]:
#Read in the csv file and convert to a Pandas dataframe
World_Happiness_2015 = pd.read_csv("datafrom_2015.csv ")
World_Happiness_2016 = pd.read_csv("datafrom_2016.csv ")
World_Happiness_2017 = pd.read_csv("datafrom_2017.csv ")
World_Happiness_2018 = pd.read_csv("datafrom_2018.csv ")
World_Happiness_2019 = pd.read_csv("datafrom_2019.csv ")

In [238]:
# mearge all dataframes 
World_Happiness = pd.concat([World_Happiness_2015,World_Happiness_2016,World_Happiness_2017,World_Happiness_2018,World_Happiness_2019])

### Viewing the dataframe
We can get a quick sense of the size of our dataset by using the shape method. This returns a tuple with the number of rows and columns in the dataset.

In [241]:
World_Happiness

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Trust..Government.Corruption.,Dystopia.Residual,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Perceptions of corruption
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,152.0,Rwanda,3.334,0.359,0.711,0.614,0.555,0.411
152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,153.0,Tanzania,3.231,0.476,0.885,0.499,0.417,0.147
153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,154.0,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.025
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,155.0,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.035
155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,156.0,South Sudan,2.853,0.306,0.575,0.295,0.010,0.091

## 1. Data Profiling:
Data profiling is a comprehensive process of examining the data available in an existing dataset and collecting statistics and information about that data.

In [244]:
World_Happiness.info

<bound method DataFrame.info of          Country          Region  Happiness Rank  Happiness Score  \
0    Switzerland  Western Europe             1.0            7.587
1        Iceland  Western Europe             2.0            7.561
2        Denmark  Western Europe             3.0            7.527
3         Norway  Western Europe             4.0            7.522
4         Canada   North America             5.0            7.427
..           ...             ...             ...              ...
151          NaN             NaN             NaN              NaN
152          NaN             NaN             NaN              NaN
153          NaN             NaN             NaN              NaN
154          NaN             NaN             NaN              NaN
155          NaN             NaN             NaN              NaN

     Standard Error  Economy (GDP per Capita)   Family  \
0           0.03411                   1.39651  1.34951
1           0.04884                   1.30232  1.40223
2           0.03328                   1.32548  1.36058
3           0.03880                   1.45900  1.33095
4           0.03553                   1.32629  1.32261
..              ...                       ...      ...
151             NaN                       NaN      NaN
152             NaN                       NaN      NaN
153             NaN                       NaN      NaN
154             NaN                       NaN      NaN
155             NaN                       NaN      NaN

     Health (Life Expectancy)  Freedom  Trust (Government Corruption)  ...  \
0                     0.94143  0.66557                        0.41978  ...
1                     0.94784  0.62877                        0.14145  ...
2                     0.87464  0.64938                        0.48357  ...
3                     0.88521  0.66973                        0.36503  ...
4                     0.90563  0.63297                        0.32957  ...
..                        ...      ...                            ...  ...
151                       NaN      NaN                            NaN  ...
152                       NaN      NaN                            NaN  ...
153                       NaN      NaN                            NaN  ...
154                       NaN      NaN                            NaN  ...
155                       NaN      NaN                            NaN  ...

     Trust..Government.Corruption.  Dystopia.Residual  Overall rank  \
0                              NaN                NaN           NaN
1                              NaN                NaN           NaN
2                              NaN                NaN           NaN
3                              NaN                NaN           NaN
4                              NaN                NaN           NaN
..                             ...                ...           ...
151                            NaN                NaN         152.0
152                            NaN                NaN         153.0
153                            NaN                NaN         154.0
154                            NaN                NaN         155.0
155                            NaN                NaN         156.0

            Country or region  Score  GDP per capita  Social support  \
0                         NaN    NaN             NaN             NaN
1                         NaN    NaN             NaN             NaN
2                         NaN    NaN             NaN             NaN
3                         NaN    NaN             NaN             NaN
4                         NaN    NaN             NaN             NaN
..                        ...    ...             ...             ...
151                    Rwanda  3.334           0.359           0.711
152                  Tanzania  3.231           0.476           0.885
153               Afghanistan  3.203           0.350           0.517
154  Central African Republic  3.083           0.026           0.000
155               South Sudan  2.853           0.306           0.575

     Healthy life expectancy  Freedom to make life choices  \
0                        NaN                           NaN
1                        NaN                           NaN
2                        NaN                           NaN
3                        NaN                           NaN
4                        NaN                           NaN
..                       ...                           ...
151                    0.614                         0.555
152                    0.499                         0.417
153                    0.361                         0.000
154                    0.105                         0.225
155                    0.295                         0.010

     Perceptions of corruption
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN
..                         ...
151                      0.411
152                      0.147
153                      0.025
154                      0.035
155                      0.091

[782 rows x 30 columns]>

In [246]:
World_Happiness.shape

(782, 30)

In [248]:
World_Happiness.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,...,Health..Life.Expectancy.,Trust..Government.Corruption.,Dystopia.Residual,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Perceptions of corruption
count,315.000000,315.000000,158.000000,315.000000,470.000000,315.000000,470.000000,315.000000,782.000000,315.000000,...,155.000000,155.000000,155.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,311.000000
mean,79.238095,5.378949,0.047885,0.899837,0.990347,0.594054,0.402828,0.140532,0.218576,2.212032,...,0.551341,0.123120,1.850238,78.500000,5.391506,0.898298,1.211026,0.661295,0.423538,0.111299
std,45.538922,1.141531,0.017146,0.410780,0.318707,0.240790,0.150356,0.115490,0.122321,0.558728,...,0.237073,0.101661,0.500028,45.104737,1.114631,0.394592,0.300310,0.252724,0.156024,0.095365
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580,...,0.000000,0.000000,0.377914,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,4.510000,0.037268,0.594900,0.793000,0.419645,0.297615,0.061315,0.130000,1.884135,...,0.369866,0.057271,1.591291,39.750000,4.514250,0.609500,1.055750,0.488250,0.322500,0.050000
50%,79.000000,5.286000,0.043940,0.973060,1.025665,0.640450,0.418347,0.106130,0.201982,2.211260,...,0.606042,0.089848,1.832910,78.500000,5.379500,0.960000,1.265500,0.699000,0.449500,0.082000
75%,118.500000,6.269000,0.052300,1.229000,1.228745,0.787640,0.516850,0.178610,0.278832,2.563470,...,0.723008,0.153296,2.144654,117.250000,6.176000,1.219500,1.457500,0.858000,0.540250,0.140500
max,158.000000,7.587000,0.136930,1.824270,1.610574,1.025250,0.669730,0.551910,0.838075,3.837720,...,0.949492,0.464308,3.117485,156.000000,7.769000,2.096000,1.644000,1.141000,0.724000,0.457000

In [250]:
World_Happiness.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Lower Confidence Interval',
       'Upper Confidence Interval', 'Happiness.Rank', 'Happiness.Score',
       'Whisker.high', 'Whisker.low', 'Economy..GDP.per.Capita.',
       'Health..Life.Expectancy.', 'Trust..Government.Corruption.',
       'Dystopia.Residual', 'Overall rank', 'Country or region', 'Score',
       'GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Perceptions of corruption'],
      dtype='object')

The process of profiling differs slightly for categorical and numerical variables due to their inherent differences.

**The two main types of data are:**
- Quantitative (numerical) data
- Qualitative (categorical) data

### Data Quality Checks
Data quality checks involve the process of ensuring that the data is accurate, complete, consistent, relevant, and reliable. 


**Here are typical steps involved in checking data quality:**

#### 1. Reliability:
Evaluate the data's source and collection process to determine its trustworthiness.

In [255]:
#In the kaggle page mentioned, the data source is Sustainable Development Solutions Network and 1 collaborator

#### 2. Timeliness: 
Ensure the data is up-to-date and reflective of the current situation or the period of interest for the analysis.

In [258]:
#Data from 2015 to 2019

#### 3. Consistency: 

Confirm that the data is consistent within the dataset and across multiple data sources. For example, the same data point should not have different values in different places.

In [261]:
#Now need to do some processes to make data Consistently 
#When I merged the data frames, I found that the order of the columns did not match,
#and their names did not match. 
#Now I will perform some operations to correct these problems and make the data consistent.'''

In [263]:
standard_columns_nameandorder = ['Country',  'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity']

In [265]:
World_Happiness_2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [267]:
#reorder dataframe for 2015
new_or1 = ['Country',  'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual' ,'Region', 'Standard Error']
World_Happiness_2015 = World_Happiness_2015[new_or1]
World_Happiness_2015.columns

Index(['Country', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual', 'Region', 'Standard Error'],
      dtype='object')

In [269]:
#reorder dataframe for 2016
new_or2 = ['Country', 'Happiness Rank', 'Happiness Score',
        
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual','Region','Lower Confidence Interval', 'Upper Confidence Interval']
World_Happiness_2016 = World_Happiness_2016[new_or2]
World_Happiness_2016.columns

Index(['Country', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual', 'Region', 'Lower Confidence Interval',
       'Upper Confidence Interval'],
      dtype='object')

In [271]:
#reorder dataframe for 2017
new_or3 = ['Country', 'Happiness.Rank', 'Happiness.Score',
       
       'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.',
       'Freedom',  'Trust..Government.Corruption.', 'Generosity',
       'Dystopia.Residual','Whisker.high',
       'Whisker.low']
World_Happiness_2017 = World_Happiness_2017[new_or3]
World_Happiness_2017.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score',
       'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.',
       'Freedom', 'Trust..Government.Corruption.', 'Generosity',
       'Dystopia.Residual', 'Whisker.high', 'Whisker.low'],
      dtype='object')

In [273]:
#reorder dataframe for 2018 & 2019
new_or4 = ['Country or region', 'Overall rank', 'Score',
       
       'GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices',  'Perceptions of corruption', 'Generosity',
       ]
World_Happiness_2018 = World_Happiness_2018[new_or4]
World_Happiness_2019 = World_Happiness_2019[new_or4]
World_Happiness_2018.columns
World_Happiness_2019.columns

Index(['Country or region', 'Overall rank', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Perceptions of corruption',
       'Generosity'],
      dtype='object')

In [275]:
#rename columns in dataframs
#2015
columns = {World_Happiness_2015.columns[i]: standard_columns_nameandorder[i] for i in range(len(standard_columns_nameandorder))}
World_Happiness_2015.rename(columns=columns, inplace=True)
#2016
columns = {World_Happiness_2016.columns[i]: standard_columns_nameandorder[i] for i in range(len(standard_columns_nameandorder))}
World_Happiness_2016.rename(columns=columns, inplace=True)
#2017
columns = {World_Happiness_2017.columns[i]: standard_columns_nameandorder[i] for i in range(len(standard_columns_nameandorder))}
World_Happiness_2017.rename(columns=columns, inplace=True)
#2018
columns = {World_Happiness_2018.columns[i]: standard_columns_nameandorder[i] for i in range(len(standard_columns_nameandorder))}
World_Happiness_2018.rename(columns=columns, inplace=True)
#2019
columns = {World_Happiness_2019.columns[i]: standard_columns_nameandorder[i] for i in range(len(standard_columns_nameandorder))}
World_Happiness_2019.rename(columns=columns, inplace=True)

In [277]:
# new merge all data frame agin 
World_Happiness_v2 = pd.concat([World_Happiness_2015,World_Happiness_2016,World_Happiness_2017,World_Happiness_2018,World_Happiness_2019])

In [279]:
World_Happiness_v2

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Region,Standard Error,Lower Confidence Interval,Upper Confidence Interval,Dystopia.Residual,Whisker.high,Whisker.low
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,Western Europe,0.03411,NaN,NaN,NaN,NaN,NaN
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,Western Europe,0.04884,NaN,NaN,NaN,NaN,NaN
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,Western Europe,0.03328,NaN,NaN,NaN,NaN,NaN
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,Western Europe,0.03880,NaN,NaN,NaN,NaN,NaN
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,North America,0.03553,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.41100,0.21700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,Tanzania,153,3.231,0.47600,0.88500,0.49900,0.41700,0.14700,0.27600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.02500,0.15800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.03500,0.23500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,South Sudan,156,2.853,0.30600,0.57500,0.29500,0.01000,0.09100,0.20200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [281]:
print("Data info for dataframe After doing consistency processes : ",World_Happiness_v2.info)

Data info for dataframe After doing consistency processes :  <bound method DataFrame.info of                       Country  Happiness Rank  Happiness Score  \
0                 Switzerland               1            7.587
1                     Iceland               2            7.561
2                     Denmark               3            7.527
3                      Norway               4            7.522
4                      Canada               5            7.427
..                        ...             ...              ...
151                    Rwanda             152            3.334
152                  Tanzania             153            3.231
153               Afghanistan             154            3.203
154  Central African Republic             155            3.083
155               South Sudan             156            2.853

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     1.39651  1.34951                   0.94143  0.66557
1                     1.30232  1.40223                   0.94784  0.62877
2                     1.32548  1.36058                   0.87464  0.64938
3                     1.45900  1.33095                   0.88521  0.66973
4                     1.32629  1.32261                   0.90563  0.63297
..                        ...      ...                       ...      ...
151                   0.35900  0.71100                   0.61400  0.55500
152                   0.47600  0.88500                   0.49900  0.41700
153                   0.35000  0.51700                   0.36100  0.00000
154                   0.02600  0.00000                   0.10500  0.22500
155                   0.30600  0.57500                   0.29500  0.01000

     Trust (Government Corruption)  Generosity  Dystopia Residual  \
0                          0.41978     0.29678            2.51738
1                          0.14145     0.43630            2.70201
2                          0.48357     0.34139            2.49204
3                          0.36503     0.34699            2.46531
4                          0.32957     0.45811            2.45176
..                             ...         ...                ...
151                        0.41100     0.21700                NaN
152                        0.14700     0.27600                NaN
153                        0.02500     0.15800                NaN
154                        0.03500     0.23500                NaN
155                        0.09100     0.20200                NaN

             Region  Standard Error  Lower Confidence Interval  \
0    Western Europe         0.03411                        NaN
1    Western Europe         0.04884                        NaN
2    Western Europe         0.03328                        NaN
3    Western Europe         0.03880                        NaN
4     North America         0.03553                        NaN
..              ...             ...                        ...
151             NaN             NaN                        NaN
152             NaN             NaN                        NaN
153             NaN             NaN                        NaN
154             NaN             NaN                        NaN
155             NaN             NaN                        NaN

     Upper Confidence Interval  Dystopia.Residual  Whisker.high  Whisker.low
0                          NaN                NaN           NaN          NaN
1                          NaN                NaN           NaN          NaN
2                          NaN                NaN           NaN          NaN
3                          NaN                NaN           NaN          NaN
4                          NaN                NaN           NaN          NaN
..                         ...                ...           ...          ...
151                        NaN                NaN           NaN          NaN
152                        NaN                NaN           NaN          NaN
153                        NaN                NaN           NaN          NaN
154                        NaN                NaN           NaN          NaN
155                        NaN                NaN           NaN          NaN

[782 rows x 17 columns]>

In [283]:
print("The shape of  dataframe After doing consistency processes : ",World_Happiness_v2.shape)

The shape of  dataframe After doing consistency processes :  (782, 17)

In [285]:
print("The Description  of  dataframe After doing consistency processes : ")
World_Happiness_v2.describe()

The Description  of  dataframe After doing consistency processes :

,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Standard Error,Lower Confidence Interval,Upper Confidence Interval,Dystopia.Residual,Whisker.high,Whisker.low
count,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,781.000000,782.000000,315.000000,158.000000,157.000000,157.000000,155.000000,155.000000,155.000000
mean,78.698210,5.379018,0.916047,1.078392,0.612416,0.411091,0.125436,0.218576,2.212032,0.047885,5.282395,5.481975,1.850238,5.452326,5.255713
std,45.182384,1.127456,0.407340,0.329548,0.248309,0.152880,0.105816,0.122321,0.558728,0.017146,1.148043,1.136493,0.500028,1.118542,1.145030
min,1.000000,2.693000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580,0.018480,2.732000,3.078000,0.377914,2.864884,2.521116
25%,40.000000,4.509750,0.606500,0.869363,0.440183,0.309768,0.054000,0.130000,1.884135,0.037268,4.327000,4.465000,1.591291,4.608172,4.374955
50%,79.000000,5.322000,0.982205,1.124735,0.647310,0.431000,0.091000,0.201982,2.211260,0.043940,5.237000,5.419000,1.832910,5.370032,5.193152
75%,118.000000,6.189500,1.236187,1.327250,0.808000,0.531000,0.156030,0.278832,2.563470,0.052300,6.154000,6.434000,2.144654,6.194600,6.006527
max,158.000000,7.769000,2.096000,1.644000,1.141000,0.724000,0.551910,0.838075,3.837720,0.136930,7.460000,7.669000,3.117485,7.622030,7.479556

In [287]:
print("The Columns  of  dataframe After doing consistency processes : ")
World_Happiness_v2.columns

The Columns  of  dataframe After doing consistency processes :

Index(['Country', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual', 'Region', 'Standard Error',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Dystopia.Residual', 'Whisker.high', 'Whisker.low'],
      dtype='object')

#### 4. Relevance: 
Assess whether the data is appropriate and applicable for the intended analysis. Data that is not relevant can skew results and lead to incorrect conclusions.

**Key considerations for relevance include:**

> 1. Sample Appropriateness: Confirm that your data sample aligns with your analysis objectives. For instance, utilizing data from the Northern region will not yield accurate insights for the Western region of the Kingdom.
>
> 2. Variable Selection: Any column will not be relevant for our analysis, we can get rid of these using the drop() method. We will set the “axis” argument to 1 since we’re dealing with columns, and set the “inplace” argument to True to make the change permanent.

#### 5. Uniqueness: 
Check for and remove duplicate records to prevent skewed analysis results.

In [66]:
# go to delete duplicates columns

#### 6. Completeness: 
Ensure that no critical data is missing. This might mean checking for null values or required fields that are empty.

We will start by checking the dataset for missing or null values. For this, we can use the isna() method which returns a dataframe of boolean values indicating if a field is null or not. To group all missing values by column, we can include the sum() method.

In [1]:
#Display number missing values per column

In [68]:
# go to clean them

#### 7. Check Accuracy:

Verify that the data is correct and precise. This could involve comparing data samples with known sources or using validation rules.

**The process includes:**
1. Validating the appropriateness of data types for the dataset.
2. Identifying outliers  using established validation  rule

In [2]:
# check columns types

In [33]:
# go to clean them

In [3]:
# check outliers

**What is an Outlier?** 
Outlier is an row/observation that appears far away and diverges from an overall pattern in a sample.

**What are the types of Outliers?**
1. Univariate: These outliers can be found when we look at distribution of a single variable
2. Multivariate: are outliers in an n-dimensional space. In order to find them, you have to look at distributions in multi-dimensions. example (hight=100, weight=100) for a person

**What causes Outliers?**
Whenever we come across outliers, the ideal way to tackle them is to find out the reason of having these outliers. The method to deal with them would then depend on the reason of their occurrence.

Let’s understand various types of outliers:

1. Data Entry Errors:- Human errors such as errors caused during data collection, recording, or entry can cause outliers in data.
2. Measurement Error: It is the most common source of outliers. This is caused when the measurement instrument used turns out to be faulty.
3. Data Processing Error: Whenever we perform data mining, we extract data from multiple sources. It is possible that some manipulation or extraction errors may lead to outliers in the dataset.
4. Sampling error: For instance, we have to measure the height of athletes. By mistake, we include a few basketball players in the sample. This inclusion is likely to cause outliers in the dataset.
5. Natural Outlier: When an outlier is not artificial (due to error), it is a natural outlier. For instance: In my last assignment with one of the renowned insurance company, I noticed that the performance of top 50 financial advisors was far higher than rest of the population. Surprisingly, it was not due to any error. Hence, whenever we perform any data mining activity with advisors, we used to treat this segment separately.


**What is the impact of Outliers on a dataset?**


![image.png](https://www.analyticsvidhya.com/wp-content/uploads/2015/02/Outlier_31.png)



**How to detect Outliers?**

1. Most commonly used method to detect outliers is visualization (Univariate Graphical Analysis).

We use 3 common visualization methods:
>- Box-plot: A box plot is a method for graphically depicting groups of numerical data through their quartiles. The box extends from the Q1 to Q3 quartile values of the data, with a line at the median (Q2). The whiskers extend from the edges of the box to show the range of the data. Outlier points are those past the end of the whiskers. Box plots show robust measures of location and spread as well as providing information about symmetry and outliers.
>
>  
>![image.png](https://miro.medium.com/v2/resize:fit:698/format:webp/1*VK5iHA2AB28HSZwWwUbNYg.png)
>
>
>- Histogram
>- Scatter Plot: A scatter plot is a mathematical diagram using Cartesian coordinates to display values for two variables for a set of data. The data are displayed as a collection of points, each having the value of one variable determining the position on the horizontal axis and the value of the other variable determining the position on the vertical axis. The points that are far from the population can be termed as an outlier.
>
>  
>![image.png](https://miro.medium.com/v2/resize:fit:4800/format:webp/1*Ov6aH-8yIwNoUxtMFwgx4g.png)
>
>

2. Using statistical method (Univariate Non-Graphical analysis):
>- Any value, which is beyond the range of -1.5 x IQR to 1.5 x IQR
 
![image.png](https://www.whatissixsigma.net/wp-content/uploads/2015/07/Box-Plot-Diagram-to-identify-Outliers-figure-1.png)

>- Use capping methods. Any value which out of range of 5th and 95th percentile can be considered as outlier
>- Data points, three or more standard deviation away from mean are considered outlier: The Z-score is the signed number of standard deviations by which the value of an observation or data point is above the mean value of what is being observed or measured. While calculating the Z-score we re-scale and center the data and look for data points that are too far from zero. These data points which are way too far from zero will be treated as the outliers. In most of the cases, a threshold of 3 or -3 is used i.e if the Z-score value is greater than or less than 3 or -3 respectively, that data point will be identified as outliers.
> - Outlier detection is merely a special case of the examination of data for influential data points and it also depends on the business understanding

In [23]:
# go to univariate graphical analysis
# go to lesson : data visualisation 1 - chart type section
# then go to univariate graphical analysis
# detect outliers using graphs varbaly

In [24]:
# go to lesson: statistics 1 then statistics 3
# then go to univariate Non graphical analysis
# detect outliers using numerical statistics

In [25]:
# go to delete ouliers

## 2. Data Cleaning: 

Preliminary findings from data profiling can lead to cleaning the data by:
- Handling missing values
- Correcting errors.
- Dealing with outliers.

-------------------

### Handling missing values:

**Why my data has missing values?**
They may occur at two stages:
1. Data Extraction: It is possible that there are problems with extraction process. Errors at data extraction stage are typically easy to find and can be corrected easily as well.
2. Data collection: These errors occur at time of data collection and are harder to correct.

**Why do we need to handle the missing data?**
To avoid:
- Bias the conclusions.
- Leading the business to make wrong decisions.

**Which are the methods to treat missing values ?**
1. Deletion: we delete rows where any of the variable is missing. Simplicity is one of the major advantage of this method, but this method reduces the power of model because it reduces the sample size.

2. Imputation: is a method to fill in the missing values with estimated ones. This imputation is one of the most frequently used methods.

    2.1. Mean/ Mode/ Median Imputation: It consists of replacing the missing data for a given attribute by the mean or median (quantitative attribute) or mode (qualitative attribute) of all known values of that variable.
    > It can be of two types:
    > - Generalized Imputation: In this case, we calculate the mean or median for all non missing values of that variable then replace missing value with mean or median.
    > - Similar case Imputation: In this case, we calculate average for each group individually of non missing values then replace the missing value based on the group.

    2.2. Constant Value
   
    2.3. Forward Filling
   
    2.4. Backward Filling

6. Prediction Model:  Prediction model is one of the sophisticated method for handling missing data. Here, we create a predictive model to estimate values that will substitute the missing data.  In this case, we divide our data set into two sets: One set with no missing values for the variable and another one with missing values. First data set become training data set of the model while second data set with missing values is test data set and variable with missing values is treated as target variable. Next, we create a model to predict target variable based on other attributes of the training data set and populate missing values of test data set.

> There are 2 drawbacks for this approach:
> - The model estimated values are usually more well-behaved than the true values
> - If there are no relationships with attributes in the data set and the attribute with missing values, then the model will not be precise for estimating missing values.

9. KNN Imputation: In this method of imputation, the missing values of an attribute are imputed using the given number of attributes that are most similar to the attribute whose values are missing. The similarity of two attributes is determined using a distance function. It is also known to have certain advantage & disadvantages.

   > **Advantages:**
   > - k-nearest neighbour can predict both qualitative & quantitative attributes
   > - Creation of predictive model for each attribute with missing data is not required
   > - Attributes with multiple missing values can be easily treated
   > - Correlation structure of the data is taken into consideration

   > **Disadvantage:**
   > - KNN algorithm is very time-consuming in analyzing large database. It searches through all the dataset looking for the most similar instances.
   > - Choice of k-value is very critical. Higher value of k would include attributes which are significantly different from what we need whereas lower value of k implies missing out of significant attributes.

--------------------

In [80]:
# go back to 6th dimention --> Completeness

### Correcting errors

-------------------

In [ ]:
# go back to 7th dimension Accuracy

### Dealing with outliers:

**How to remove Outliers?**
Most of the ways to deal with outliers are similar to the methods of missing values like deleting rows, transforming them, binning them, treat them as a separate group, imputing values and other statistical methods. Here, we will discuss the common techniques used to deal with outliers:

1. Deleting rows: We delete outlier values if it is due to data entry error, data processing error or outlier rows are very small in numbers. We can also use trimming at both ends to remove outliers.

2. Imputing: Like imputation of missing values, we can also impute outliers. We can use mean, median, mode imputation methods. Before imputing values, we should analyse if it is natural outlier or artificial. If it is artificial, we can go with imputing values. We can also use statistical model to predict values of outlier rows and after that we can impute it with predicted values.

3. Treat separately: If there are significant number of outliers, we should treat them separately in the statistical model. One of the approach is to treat both groups as two different groups and build individual model for both groups and then combine the output.

## 3. Univariate Analysis: 

This involves examining single variables to understand their characteristics (distribution, central tendency, dispersion, and shape).

We calculate **numerical values** about the data that tells us about the distribution of the data. We also **draw graphs** showing visually how the data is distributed. **To answer the following questions about Features/characteristics of Data:**
- Where is the center of the data? (location)
- How much does the data vary? (scale)
- What is the shape of the data? (shape)

**The benefits of this analysis:**
Statistics summary gives a high-level idea to identify whether the data has any outliers, data entry error, distribution of data such as the data is normally distributed or left/right skewed

**In this step, we will explore variables one by one using following approaches:**

### 1. Univariate Graphical Analysis:
Method to perform uni-variate analysis will depend on whether the variable type is categorical or numerical.

#### I. Categorical Variables:

we’ll use frequency table to understand distribution of each category
- Bar Chart (Ordinal) - Orderd
- Pie Chart (Nominal) - non Orderd

#### II. Numerical Variables:

we need to understand the central tendency and spread of the variable (Descriptive Analysis) using:
   - Box plot
   - Histogram

### 2. Univariate Non-Graphical analysis: 

- Where is the center of the data? (location) --> **Measures of central tendency**
- How much does the data vary? (scale) --> **Measure of variability**
- What is the shape of the data? (shape) --> **Measures of variation combined with an average (measure of center) gives a good picture of the distribution of the data.**

## 4. Bivariate/Multivariate Analysis:

Here, you look at the relationships between two or more variables. This can involve looking for correlations, patterns, and trends that suggest a relationship or an association.

We can perform bi-variate analysis for any combination of categorical and numerical variables. The combination can be:
| bi-variate variables   | Plot type |
| ------------- | ------------- |
| Categorical & Categorical| Stacked Bar Chart |
| Categorical & numerical  | scatter plot, histogram, box plot|
| numerical  & numerical  | Scatter plot, line chart| 


Multivariate Analysis:
- Heat map
- Bar Chart
- Scatter Chart
- Line Chart

**Categorical & Categorical --> (Stacked Column Chart)**

**Categorical & numerical --> (scatter plot, histogram, box plot)**

**numerical & numerical --> (Scatter plot, line chart)**

We could also use a correlation matrix to get more specific information about the relationship between these two variables.